server:
  port: 6666

spring:
  application:
    name: foodie-test-redis

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6400
    timeout: 1000
    lettuce:
      shutdown-timeout: 200ms
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0

