version: '3'
services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    container_name: zoo1
    privileged: true
    ports:
      - 2181:2181
    volumes:
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk1/data:/data"
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk1/datalog:/datalog"
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.55.0.11

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    container_name: zoo2
    privileged: true
    ports:
      - 2182:2181
    volumes:
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk2/data:/data"
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk2/datalog:/datalog"
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.55.0.12

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    container_name: zoo3
    privileged: true
    ports:
      - 2183:2181
    volumes:
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk3/data:/data"
      - "/Users/ivy-dev/Desktop/java/zookeeper/zk3/datalog:/datalog"
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.55.0.13

networks:
  default:
    external:
      name: zookeeper_network
