server:
  port: 8882

elastic:
  job:
    zk:
      serverLists: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
      namespace: elastic-job

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3320/elasticjob?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 123456
