version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100  # 修改为本机地址
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
  kafka-manager:
    image: sheepkiller/kafka-manager # 镜像：开源的web管理kafka集群的界面
    environment:
      ZK_HOSTS: 192.168.99.100 # 修改为本机地址
    ports:
      - "9000:9000"
