server:
  port: 8881

dataflowJob:
  cron: 0/10 * * * * ?
  shardingItemParameters: 0=Beijing,1=Shanghai
  shardingTotalCount: 2

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3320/elasticjob?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 123456

