server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: foodie-rabbit-producer
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    addresses: 127.0.0.1:5672
    connection-timeout: 15000
    password: root
    username: root
    virtual-host: /
    # 表示消费者消费成功以后需要手工进行签收(ack) 默认为auto
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1

