server:
  port: 8066
  tomcat:
    uri-encoding: UTF-8

fdfs:
  # 链接超时
  connect-timeout: 600
  network-timeout: 600
  # 读取时间
  so-timeout: 60
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.1.3:22122