server:
  port: 65000

spring:
  application:
    name: foodie-test-gateway-mysql-redis

  # 数据源的相关配置
  datasource:
    url: jdbc:mysql://localhost:3320/gateway-mysql?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6400
    timeout: 1000
    lettuce:
      shutdown-timeout: 200ms
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0

mybatis:
  type-aliases-package: com.imooc.springcloud.domain          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml                    # mapper映射文件
  #监测每一次调用数据库的sql语句在控制台打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always