elastic:
  job:
    zk:
      namespace: elastic-job
      serverLists: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183

server:
  context-path: /test
  port: 8001
spring:
  application:
    name: test
  rabbitmq:
    addresses: 127.0.0.1:5672
    connection-timeout: 15000
    listener:
      simple:
        auto-startup: false
    password: root
    username: root
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: /
